import { Router } from "express";
import { adminRoutes } from "./admin-routes";
import { aiReviewRoutes } from "./ai-review-routes";
import { assignmentRoutes } from "./assignment-routes";
import { authRoutes } from "./auth-routes";
import { chatbotRoutes } from "./chatbot-routes";
import { dashboardRoutes } from "./dashboard-routes";
import { debugRoutes } from "./debug-routes";
import { dictionaryRoutes } from "./dictionary-routes";
import { exerciseRoutes } from "./exercise-routes";
import { leaderboardRoutes } from "./leaderboard-routes";
import { listeningRoutes } from "./listening-routes";
import { paymentRoutes } from "./payment-routes";
import { progressRoutes } from "./progress-routes";
import { healthcheckRoutes } from "./healthcheck-routes";
import { readingExerciseRoutes } from "./reading-exercise-routes";
import { reviewRoutes } from "./review-routes";
import { sentenceWritingRoutes } from "./sentence-writing-routes";
import { speakingRoutes } from "./speaking-routes";
import { statisticsRoutes } from "./statistics-routes";
import { transactionRoutes } from "./transaction-routes";
import { teacherReviewRoutes } from "./teacher-review-routes";
import { userManagementRoutes } from "./user-management-routes";
import { userProgressRoutes } from "./user-progress-routes";
import { usersRoutes } from "./users-routes";

export const apiRoutes = Router();

apiRoutes.use("/auth", authRoutes);
apiRoutes.use("/admin", adminRoutes);
apiRoutes.use("/AIReview", aiReviewRoutes);
apiRoutes.use("/aireview", aiReviewRoutes);
apiRoutes.use("/Assignment", assignmentRoutes);
apiRoutes.use("/assignment", assignmentRoutes);
apiRoutes.use("/Chatbot", chatbotRoutes);
apiRoutes.use("/chatbot", chatbotRoutes);
apiRoutes.use("/Dashboard", dashboardRoutes);
apiRoutes.use("/dashboard", dashboardRoutes);
apiRoutes.use("/Debug", debugRoutes);
apiRoutes.use("/debug", debugRoutes);
apiRoutes.use("/Dictionary", dictionaryRoutes);
apiRoutes.use("/dictionary", dictionaryRoutes);
apiRoutes.use("/Healthcheck", healthcheckRoutes);
apiRoutes.use("/healthcheck", healthcheckRoutes);
apiRoutes.use("/exercise", exerciseRoutes);
apiRoutes.use("/Exercise", exerciseRoutes);
apiRoutes.use("/Leaderboard", leaderboardRoutes);
apiRoutes.use("/leaderboard", leaderboardRoutes);
apiRoutes.use("/progress", progressRoutes);
apiRoutes.use("/Progress", progressRoutes);
apiRoutes.use("/User", userProgressRoutes);
apiRoutes.use("/user", userProgressRoutes);
apiRoutes.use("/user-management", userManagementRoutes);
apiRoutes.use("/users", usersRoutes);
apiRoutes.use("/statistics", statisticsRoutes);
apiRoutes.use("/Statistics", statisticsRoutes);
apiRoutes.use("/Listening", listeningRoutes);
apiRoutes.use("/listening", listeningRoutes);
apiRoutes.use("/Speaking", speakingRoutes);
apiRoutes.use("/speaking", speakingRoutes);
apiRoutes.use("/ReadingExercise", readingExerciseRoutes);
apiRoutes.use("/readingexercise", readingExerciseRoutes);
apiRoutes.use("/Review", reviewRoutes);
apiRoutes.use("/review", reviewRoutes);
apiRoutes.use("/SentenceWriting", sentenceWritingRoutes);
apiRoutes.use("/sentencewriting", sentenceWritingRoutes);
apiRoutes.use("/payment", paymentRoutes);
apiRoutes.use("/Payment", paymentRoutes);
apiRoutes.use("/Transaction", transactionRoutes);
apiRoutes.use("/transaction", transactionRoutes);
apiRoutes.use("/TeacherReview", teacherReviewRoutes);
apiRoutes.use("/teacherreview", teacherReviewRoutes);
